// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                 = require("@glennsl/bs-jest/src/jest.js");
var ReasonReact          = require("reason-react/src/ReasonReact.js");
var Page$ReactTemplate   = require("../page.bs.js");
var ReactShallowRenderer = require("bs-react-test-renderer/src/ReactShallowRenderer.bs.js");

describe("App", (function () {
        return Jest.test("renders", (function () {
                      var tree = ReactShallowRenderer.renderWithRenderer(ReasonReact.element(/* None */0, /* None */0, Page$ReactTemplate.make("Hello world!", "will and kate!!!", /* array */[])));
                      return Jest.Expect[/* toMatchSnapshot */16](Jest.Expect[/* expect */0](tree));
                    }));
      }));

/*  Not a pure module */
