// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Cn          from "re-classnames/src/Cn.bs.js";
import * as Curry       from "bs-platform/lib/es6/curry.js";
import * as React       from "react";
import * as PageScss    from "./page.scss";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("Page");

function handleClick(_, _$1) {
  console.log("clicked!");
  return /* () */0;
}

function make(one, two, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("div", {
                  className: Cn.make(/* :: */[
                        PageScss.background,
                        /* :: */[
                          Cn.ifBool(/* true */1, PageScss.text),
                          /* [] */0
                        ]
                      ]),
                  onClick: Curry._1(self[/* handle */0], handleClick)
                }, one + (" " + two));
    });
  return newrecord;
}

console.log(Cn.make(/* :: */[
          PageScss.background,
          /* :: */[
            Cn.ifBool(/* true */1, PageScss.text),
            /* [] */0
          ]
        ]));

export {
  component   ,
  handleClick ,
  make        ,
  
}
/* component Not a pure module */
